### ISSUE TITLE
Double Puppeting instructions are confusing

### ISSUE THREAD

**Issue by chadkouse** [mautrix/imessage#224]
I've tried to follow a few different methods of enabling double puppeting with no success.  It *seems* like the current recommendation is to use the app service method.  I have that set up on my home server but I can't get the imessage bridge to work with it.  I don't know that the imessage bridge supports it though -- I don't see anything mentioned about a `double_puppet` config setting in the code.  I did see [this](https://github.com/mautrix/imessage/blob/892f056ea4ffd7e14e19bf7a0de354270ee6b070/custompuppet.go#L88) where it looks like something special happens if you set your shared secret to "appservice" but I didn't get that to work either.

Usually I just see in the logs that it's dropping a message because double puppeting isn't set up, but with the "appservice" shared secret I got an error about a failed login.

What is the current method for enabling double puppeting?  I asked in the matrix channel last night and nobody responded so I thought I'd try here.

**Comment by ethan-leba** [comment]
I've also been struggling with this, were you able to figure out a solution @chadkouse ?

**Comment by chadkouse** [comment]
@ethan-leba I figured this out... I think.  The [double puppet docs](https://docs.mau.fi/bridges/general/double-puppeting.html) seem to not quite work for this bridge.  For this bridge you **do** need to modify the appservice registration.

1. add a namespace to the imessage bridge appservice regisration.  The following has it added to the example regisration file:
```
# appservice -> id from the config
id: imessage
# appservice -> as_token and hs_token from the config
as_token: random string
hs_token: random string
namespaces:
  users:
    # The localpart here is username_template from the config, but .+ instead of {{.}}
    - regex: '@imessage_.+:example\.com'
      exclusive: true
    # Localpart here is appservice -> bot -> username from the config
    - regex: '@imessagebot:example\.com'
      exclusive: true
    # The following is to enable auto double puppeting for any users matching the regex
    # Replace your\.domain with your server name (escape dots for regex)
    - regex: '@.*:your\.domain'
      # This must be false so the appservice doesn't take over all users completely.
      exclusive: false

# Address that Synapse uses to contact mautrix-wsproxy, this might be
# something like "http://mautrix-wsproxy:29331" in a docker-compose
# setup or "http://localhost:29331" on bare metal; if using Docker you
# should make sure your networking is setup so this address is
# reachable from from inside the synapse container
url: "http://wsproxy.address:29331"
# Put a new random string here, it doesn't affect anything else
sender_localpart: random string
rate_limited: false
```

2. Set the `bridge` -> `login_shared_secret` to the magic string `appservice` in the bridge config.yaml file:
```
...
bridge:
  ...
  login_shared_secret: appservice
  ...
...
```

That seems to be it!
